-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2026-09-23 12:51:46 CST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE agent
    (
     id          INTEGER  NOT NULL ,
     name        VARCHAR2 (100)  NOT NULL ,
     slug        VARCHAR2 (100)  NOT NULL ,
     photo       VARCHAR2 (255) ,
     email       VARCHAR2 (255)  NOT NULL ,
     phone       VARCHAR2 (20) ,
     bio         CLOB ,
     bio_es      CLOB ,
     agent_order INTEGER  NOT NULL ,
     is_active   CHAR (1)  NOT NULL ,
     created_at  TIMESTAMP  NOT NULL ,
     updated_at  TIMESTAMP  NOT NULL ,
     user_id     INTEGER
    )
;
CREATE UNIQUE INDEX agent__IDX ON agent
    (
     user_id ASC
    )
;

ALTER TABLE agent
    ADD CONSTRAINT agent_PK PRIMARY KEY ( id ) ;

ALTER TABLE agent
    ADD CONSTRAINT agent_email_UN UNIQUE ( email ) ;

ALTER TABLE agent
    ADD CONSTRAINT agent_slug_UN UNIQUE ( slug ) ;

CREATE TABLE category
    (
     id             INTEGER  NOT NULL ,
     name           VARCHAR2 (100)  NOT NULL ,
     slug           VARCHAR2 (100)  NOT NULL ,
     category_order INTEGER  NOT NULL ,
     group_type     VARCHAR2 (100)  NOT NULL
    )
;

ALTER TABLE category
    ADD
    CHECK (group_type IN ('property_area', 'property_feature', 'property_label', 'property_status', 'property_type'))
;

ALTER TABLE category
    ADD CONSTRAINT category_PK PRIMARY KEY ( id ) ;

ALTER TABLE category
    ADD CONSTRAINT category_slug_UN UNIQUE ( slug ) ;

CREATE TABLE lead
    (
     id            INTEGER  NOT NULL ,
     first_name    VARCHAR2 (100)  NOT NULL ,
     last_name     VARCHAR2 (100)  NOT NULL ,
     email         VARCHAR2 (100)  NOT NULL ,
     phone         VARCHAR2 (20) ,
     interested_in VARCHAR2 (255)  NOT NULL ,
     budget        NUMBER (14,2) ,
     status        VARCHAR2 (100)  NOT NULL ,
     notes         CLOB ,
     created_at    TIMESTAMP  NOT NULL ,
     updated_at    TIMESTAMP  NOT NULL ,
     agent_id      INTEGER
    )
;

ALTER TABLE lead
    ADD CONSTRAINT lead_PK PRIMARY KEY ( id ) ;

CREATE TABLE open_house
    (
     id           INTEGER  NOT NULL ,
     starts_at    DATE  NOT NULL ,
     ends_at      DATE  NOT NULL ,
     notes        CLOB ,
     notes_es     CLOB ,
     is_published CHAR (1)  NOT NULL ,
     created_at   TIMESTAMP  NOT NULL ,
     updated_at   TIMESTAMP  NOT NULL ,
     property_id  INTEGER  NOT NULL
    )
;

ALTER TABLE open_house
    ADD CONSTRAINT open_house_PK PRIMARY KEY ( id ) ;

CREATE TABLE property
    (
     id                  INTEGER  NOT NULL ,
     name                VARCHAR2 (100)  NOT NULL ,
     slug                VARCHAR2 (255)  NOT NULL ,
     address             VARCHAR2 (255) ,
     city                VARCHAR2 (100)  NOT NULL ,
     state               VARCHAR2 (100)  NOT NULL ,
     country             VARCHAR2 (100)  NOT NULL ,
     zip                 VARCHAR2 (10)  NOT NULL ,
     latitude            NUMBER (10,7) ,
     longitude           NUMBER (10,7) ,
     is_featured         CHAR (1)  NOT NULL ,
     is_active           CHAR (1)  NOT NULL ,
     is_sold             CHAR (1)  NOT NULL ,
     sold_date           DATE ,
     price_usd           NUMBER (15,3)  NOT NULL ,
     price_mxn           NUMBER (15,3)  NOT NULL ,
     show_both_prices    CHAR (1)  NOT NULL ,
     description         CLOB ,
     description_es      CLOB ,
     lot_meters          FLOAT  NOT NULL ,
     construction_meters FLOAT  NOT NULL ,
     bedrooms            INTEGER  NOT NULL ,
     bathrooms           INTEGER  NOT NULL ,
     half_bathrooms      INTEGER  NOT NULL ,
     parking_spaces      INTEGER  NOT NULL ,
     notes               CLOB ,
     property_order      INTEGER  NOT NULL ,
     created_at          TIMESTAMP  NOT NULL ,
     updated_at          TIMESTAMP  NOT NULL
    )
;

ALTER TABLE property
    ADD CONSTRAINT property_PK PRIMARY KEY ( id ) ;

ALTER TABLE property
    ADD CONSTRAINT property_slug_UN UNIQUE ( slug ) ;

CREATE TABLE property_agent
    (
     property_id INTEGER  NOT NULL ,
     agent_id    INTEGER  NOT NULL
    )
;

ALTER TABLE property_agent
    ADD CONSTRAINT Relation_3_PK PRIMARY KEY ( property_id, agent_id ) ;

CREATE TABLE property_category
    (
     property_id INTEGER  NOT NULL ,
     category_id INTEGER  NOT NULL
    )
;

ALTER TABLE property_category
    ADD CONSTRAINT Relation_4_PK PRIMARY KEY ( property_id, category_id ) ;

CREATE TABLE property_image
    (
     id          INTEGER  NOT NULL ,
     path        VARCHAR2 (255)  NOT NULL ,
     type        VARCHAR2 (30) DEFAULT 'gallery'  NOT NULL ,
     sort_order  INTEGER  NOT NULL ,
     property_id INTEGER  NOT NULL
    )
;

ALTER TABLE property_image
    ADD
    CHECK (type IN ('featured_image', 'gallery'))
;

ALTER TABLE property_image
    ADD CONSTRAINT property_image_PK PRIMARY KEY ( id ) ;

CREATE TABLE property_inquiry
    (
     id          INTEGER  NOT NULL ,
     name        VARCHAR2 (100)  NOT NULL ,
     email       VARCHAR2 (255)  NOT NULL ,
     phone       VARCHAR2 (20) ,
     message     CLOB  NOT NULL ,
     created_at  TIMESTAMP  NOT NULL ,
     property_id INTEGER  NOT NULL
    )
;

ALTER TABLE property_inquiry
    ADD CONSTRAINT property_inquiry_PK PRIMARY KEY ( id ) ;

CREATE TABLE "user"
    (
     id         INTEGER  NOT NULL ,
     name       VARCHAR2 (100)  NOT NULL ,
     email      VARCHAR2 (255)  NOT NULL ,
     password   VARCHAR2 (255)  NOT NULL ,
     role       VARCHAR2 (100)  NOT NULL ,
     photo      VARCHAR2 (255) ,
     is_enabled CHAR (1)  NOT NULL
    )
;

ALTER TABLE "user"
    ADD CONSTRAINT user_PK PRIMARY KEY ( id ) ;

ALTER TABLE "user"
    ADD CONSTRAINT user_email_UN UNIQUE ( email ) ;

ALTER TABLE agent
    ADD CONSTRAINT agent_user_FK FOREIGN KEY
    (
     user_id
    )
    REFERENCES "user"
    (
     id
    )
    ON DELETE SET NULL
;

ALTER TABLE lead
    ADD CONSTRAINT lead_agent_FK FOREIGN KEY
    (
     agent_id
    )
    REFERENCES agent
    (
     id
    )
;

ALTER TABLE open_house
    ADD CONSTRAINT open_house_property_FK FOREIGN KEY
    (
     property_id
    )
    REFERENCES property
    (
     id
    )
    ON DELETE CASCADE
;

ALTER TABLE property_image
    ADD CONSTRAINT property_image_property_FK FOREIGN KEY
    (
     property_id
    )
    REFERENCES property
    (
     id
    )
    ON DELETE CASCADE
;

ALTER TABLE property_inquiry
    ADD CONSTRAINT property_inquiry_property_FK FOREIGN KEY
    (
     property_id
    )
    REFERENCES property
    (
     id
    )
    ON DELETE CASCADE
;

ALTER TABLE property_agent
    ADD CONSTRAINT Relation_3_agent_FK FOREIGN KEY
    (
     agent_id
    )
    REFERENCES agent
    (
     id
    )
;

ALTER TABLE property_agent
    ADD CONSTRAINT Relation_3_property_FK FOREIGN KEY
    (
     property_id
    )
    REFERENCES property
    (
     id
    )
;

ALTER TABLE property_category
    ADD CONSTRAINT Relation_4_category_FK FOREIGN KEY
    (
     category_id
    )
    REFERENCES category
    (
     id
    )
    ON DELETE CASCADE
;

ALTER TABLE property_category
    ADD CONSTRAINT Relation_4_property_FK FOREIGN KEY
    (
     property_id
    )
    REFERENCES property
    (
     id
    )
    ON DELETE CASCADE
;

CREATE SEQUENCE agent_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER agent_id_TRG
BEFORE INSERT ON agent
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := agent_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE category_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER category_id_TRG
BEFORE INSERT ON category
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := category_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE lead_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER lead_id_TRG
BEFORE INSERT ON lead
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := lead_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE open_house_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER open_house_id_TRG
BEFORE INSERT ON open_house
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := open_house_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE property_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER property_id_TRG
BEFORE INSERT ON property
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := property_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE property_image_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER property_image_id_TRG
BEFORE INSERT ON property_image
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := property_image_id_SEQ.NEXTVAL;
END;
/

CREATE SEQUENCE property_inquiry_id_SEQ
START WITH 1
    NOCACHE
    ORDER ;

CREATE OR REPLACE TRIGGER property_inquiry_id_TRG
BEFORE INSERT ON property_inquiry
FOR EACH ROW
WHEN (NEW.id IS NULL)
BEGIN
    :NEW.id := property_inquiry_id_SEQ.NEXTVAL;
END;
/



-- Oracle SQL Developer Data Modeler Summary Report:
--
-- CREATE TABLE                            10
-- CREATE INDEX                             1
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
--
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
--
-- REDACTION POLICY                         0
--
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
--
-- ERRORS                                   0
-- WARNINGS                                 0
